### ISSUE TITLE
Unable to POST with form-data?

### ISSUE THREAD

**Issue by mindplay-dk** [fain182/diciotto#2]
We've been having some problems trying to do a basic `POST` with plain form-data.

On one system, it simply didn't post the form-data body.

On my own system, it seems to segfault deep inside curl somewhere - there's no meaningful error-message, so I tried shuffling around a `die()` statement, and it appears to die *while* returning from the `sendRequest()` method.

I attempted to add test-coverage for this:

https://github.com/fain182/diciotto/compare/master...mindplay-dk:post-coverage

Can you try this our on your own system and see if you have any luck?

**Comment by fain182** [comment]
I added the test and I had a segmentation fault too :-(

https://travis-ci.org/fain182/diciotto/builds/551880831
It seems that depends on the PHP version, for 7.1 there is a strange result (but it could be a my error), PHP 7.2 and 7.3 have a segmentation fault.

I will update you when I will understand something more..

**Comment by fain182** [comment]
v.1.0.4 released with the fix. :tada:
